Fix error when hash option is used thx to @tiyeuse
`cme smb 192.168.57.5 -u users.txt -H 8846f7eaee8fb117ad06bdd830b7586c``

=> 

UnboundLocalError: local variable 'ntlm_hash_file' referenced before assignment